### ISSUE TITLE
Synthetic miRNA-seq data for human genome

### ISSUE THREAD

**Issue by vivekruhelaIIITD** [itmat/CAMPAREE#8]
Can we generate the synthetic miRNA-seq data for the human genome?

**Comment by brainfood** [comment]
CAMPAREE is designed to simulate transcriptomes before any sequencing has been performed on them. The transcriptomes it currently simulates do not include small or micro RNAs. This is because we designed it to estimate transcript abundances and parameters from real FASTQ files, and these operations assume the input data are from pre-mRNA- and mRNA-sized transcripts.

That being said, I think you could modify the CAMPAREE output to include miRNA sequences, though CAMPAREE wouldn't be estimating their abundances from real data. If you want a full transcriptome that includes simulated miRNAs, you could run CAMPAREE once, priming it with RNA-seq data from full-sized transcripts. Make sure the input annotation includes entries for small/miRNAs. Then you could take the CAMPAREE output files for quantification and alleleic imbalance, and manually adjust the abundance values for your miRNAs of interest. Then re-run CAMPAREE, but provide it will all the output from the first CAMPAREE run, including the files where you modified the miRNA expression (see various 'optional_inputs' in the CAMPAREE config file).

Note, this will get you a simulated transcriptome that includes miRNA sequences, and not simulated miRNA-seq data. For that, you'd need to take the CAMPAREE input and use it to as input for a library prep simulator (see [this section](https://camparee.readthedocs.io/en/latest/camparee_output.html) of the CAMPAREE docs for further instructions).

The [BEERS2](https://github.com/itmat/BEERS2) simulator is built to work with CAMPAREE output, however it currently simulates full-length RNA-seq experiments, which include various steps that deviate from typical small RNA-seq library preps (e.g. size selection steps removing short molecules, adapter ligation after cDNA generation). You could modify the BEERS2 config file to skip the fragmentation steps, and tweak the parameters for (or skip)  some other steps to more closely resemble a small RNA-seq protocol. If that's something you're interested in pursuing, we can talk in more detail.

**Comment by vivekruhelaIIITD** [comment]
Sorry for the late response. So, I think BEERS2 can not be used for miRNA seq data generation, but we can tweak the CAMPAREE tool. My goal is to generate only synthetic miRNA seq data (not with full transcriptome) so that I know the abundance of each synthetic sequence and can check the performance of the newly developed tool.  I think CAMPAREE can be helpful in different ways and different sets of experiments. Thanks for the suggestion. It's a nice work.
